name: Publish Docker Image
on: [push]
jobs:
  push_image_to_registry:
  name: Push Docker Image to registry
  runs-on: ubuntu-latest
  steps:
  -name: Check out the repo
  uses: actions/checkout@v4.1.3
  
-name: Log in to Docker Hub
uses: docker/login-action@v3.1.0
with:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}    
- name:  Extract Metadata (tags. labels) for docker
  id: meta
uses: docker/metadata-action@v5.5.1
with:
   images: motolaadegboyega/github-action-repo
- name: Build and Push the Docker Image
uses: docker/build-push-action@v5.3.0
with:
    context: .
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}

  
  
